// <auto-generated />
namespace University_ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class PHDStudent_Model_Update : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PHDStudent_Model_Update));
        
        string IMigrationMetadata.Id
        {
            get { return "202012151223488_PHDStudent_Model_Update"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
