// <auto-generated />
namespace University_ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Employee_FullTimeFaculty_LabManager_Secretary_LabManager : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Employee_FullTimeFaculty_LabManager_Secretary_LabManager));
        
        string IMigrationMetadata.Id
        {
            get { return "202012201409541_Employee_FullTimeFaculty_LabManager_Secretary_LabManager"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
