// <auto-generated />
namespace University_ERP.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class ParTime_and_PHD_Student_Model_Added : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ParTime_and_PHD_Student_Model_Added));
        
        string IMigrationMetadata.Id
        {
            get { return "202012111410288_ParTime_and_PHD_Student_Model_Added"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
